# -*- coding: utf-8 -*-
"""PythonProject1_DataAnalyst.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rMV8h1-VmtmjSE1tOXN2rxBjTLf-T1FV

**Automatic File Sorter in File Explorer**
"""

import os,shutil

fileNames = os.listdir()
fileNames

folder = ['CSV File','JPG File','DOC File']
for i in range(0,len(folder)):
  if not os.path.exists(folder[i]):
    os.makedirs(folder[i])

for file in fileNames:
  if '.csv' in file and not os.path.exists('CSV File/'+file):
    shutil.move(file,'CSV File/'+file)
  elif '.doc' in file and not os.path.exists('DOC File/'+file):
    shutil.move(file,'DOC File/'+file)
  elif '.jpg' in file or '.jpeg' in file and not os.path.exists('JPG File/'+file):
    shutil.move(file,'JPG File/'+file)